### PR TITLE
Copy updates

### PR DESCRIPTION
**Pull request by Shinsina**
Various images showing off the copy updates and new images etc.

Screen Shot 2022-02-17 at 3 12 54 PM
Screen Shot 2022-02-17 at 3 13 02 PM
Screen Shot 2022-02-17 at 3 13 54 PM
Screen Shot 2022-02-17 at 3 12 06 PM
Screen Shot 2022-02-17 at 3 12 12 PM
Screen Shot 2022-02-17 at 3 12 49 PM
Screen Shot 2022-02-17 at 3 14 17 PM
Screen Shot 2022-02-17 at 3 14 32 PM
Screen Shot 2022-02-17 at 3 16 03 PM
Screen Shot 2022-02-17 at 3 16 07 PM

### CODE REVIEW

**Comment by Shinsina** [comment]
[HO Soy: Update Market Outlook Content](https://trello.com/c/nxHc65RP/29-ho-soy-update-market-outlook-content)

**Comment by Shinsina** [comment]
[HO Soy: Update Marketing & Logistics Content](https://trello.com/c/6dLtsMjJ/30-ho-soy-update-marketing-logistics-content)

**Comment by Shinsina** [comment]
[HO Soy: Update Soft IP Program Content](https://trello.com/c/CyS38ut0/31-ho-soy-update-soft-ip-program-content)

**Comment by Shinsina** [comment]
[HO Soy: Transportation & Storage Costs Content](https://trello.com/c/dVsRaOh9/32-ho-soy-transportation-storage-costs-content)

**Comment by Shinsina** [comment]
[HO Soy: Why High Oleic Content](https://trello.com/c/3FxZGyp9/33-ho-soy-why-high-oleic-content)

**Comment by Shinsina** [comment]
[HO Soy: NEW PAGE Competitive Yields](https://trello.com/c/sxqyZWpT/35-ho-soy-new-page-competitive-yields)

**Comment by Shinsina** [comment]
[HO Soy: NEW PAGE On-Farm Profit Potential](https://trello.com/c/NjZMpWWk/36-ho-soy-new-page-on-farm-profit-potential)

**Comment by Shinsina** [comment]
[HO Soy: NEW PAGE Meeting Market Demand](https://trello.com/c/nSJP5yhW/34-ho-soy-new-page-meeting-market-demand)

**Review by B77Mills — APPROVED** [review]

**Pull request merged**
