### PR TITLE
Create grain elevator locator query and page

### PR DESCRIPTION
**Pull request by Shinsina**
Initial state (desktop):
image

Initial state (mobile):
image

Results (desktop):
image

Results (mobile):
image

No results state:
image

Loading state:
image

Error state:
image

### CODE REVIEW

**Comment by Shinsina** [comment]
[Elevator Locator Tool](https://trello.com/c/wUGe4tM5/13-elevator-locator-tool)

**Comment by Shinsina** [comment]
Screen Shot 2021-07-20 at 10 58 14 AM

**Comment by Shinsina** [comment]
Ignore the GitGuardian checks I had forgotten to remove my personal Google API Key on a couple of the commits.

**Comment by brandonbk** [comment]
@Shinsina - assuming the search works as-is, I would be willing to merge as-is or perhaps merge into a "beta" branch if we can clean up the presentation a bit.  Let's review together.

**Comment by Shinsina** [comment]
Screen Shot 2021-07-22 at 9 54 37 AM
Screen Shot 2021-07-22 at 9 54 53 AM

**Comment by Shinsina** [comment]
Screen Shot 2021-07-23 at 2 01 05 PM
Screen Shot 2021-07-23 at 2 01 13 PM
Screen Shot 2021-07-23 at 2 01 17 PM

**Pull request merged**
